### ISSUE TITLE
Why use `sc` in`lineFold`?

### ISSUE THREAD

**Issue by wataru86** [mrkkrp/markkarpov.com#60]
I read the section [Adding line folds](https://markkarpov.com/megaparsec/megaparsec.html#adding-line-folds) in "Megaparsec tutorial from IH book".
However, I couldn't understand why use normal space consumer `sc` in the last line of example.

I tried to feed the following input. 
```
something
    one
        two
          three
        four
    five
```
I got this result.
```
*Main> parseTest (pItemList <* eof) "something\n    one\n        two\n         three\n        four\n    five"
("something",[("one",["two three","four"]),("five",[])])
```
The same result was obtained by changing `sc` to `scn`.
Why use `sc` in`lineFold`?

**Comment by mrkkrp** [comment]
I don't have a clear image of what is happening there anymore, so a proper answer would require refreshing my memory by spending some time digging this. However, I think that the situation is the following:

* Components of a line fold can only be more indented than its start.
* `sc'` consumes whitespace with newlines in such a way that after consuming whitespace the column is greater than initial column.
* To stop, `sc'` should encounter the opposite situation, that is, column after consumption should be less (or equal?) than inital column. At that point it stops and `sc` is used to pick up whitespace before that new thing that will start at that column.
* Previously used `sc'` already probed whitespace with space consumer which consumes newlines. So it only logical to also consume newlines when picking up trailing whitespace.
* Thus, I think you are right and we can use `spn` there instead of `sp`.

I'd merge a PR correcting this.

**Comment by wataru86** [comment]
I pretty much got it!
Thanks!

**Comment by mrkkrp** [comment]
I updated the explanation incorporating details from this thread. Closing.
